# STUDENT PROFILE PROGRAM

name = input("What is your full name: ")
age = input("How old are you: ")
sid = input("What is your student ID: ")
city = input("What city do you live in: ")
university = input("What university do you attend: ")
department = input("What department are you in: ")
email = input("What is your email address: ")
phone = input("What is your phone number: ")
fav_lang = input("What is your favorite programming language: ")
goal = input("What is your goal in programming: \n")

print("===============================")
print("     AKIBA STUDENT PROFILE")
print("===============================")
print("Name: ", name)
print("Age: ", age)
print("Student ID: ", sid)
print("City: ", city)
print("University: ", university)
print("Department: ", department)
print("Email: ", email)
print("Phone: ", phone)
print("Favorite Programming Language: ", fav_lang)
print("Goal in Programming: ", goal)
print("===============================")